CREATE DATABASE IF NOT EXISTS DESAFIO_CURSO_JAVA;

USE DESAFIO_CURSO_JAVA

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    SALARIO DECIMAL(8,2),
    ID_GERENTE INT
);

CREATE TABLE IF NOT EXISTS DESENVOLVEDORES (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL ENUM('ESTAGIARIO', 'JUNIOR', 'PLENO', 'SENIOR'),
    CONSTRAINT FK_DESENVOLVEDOR_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS (ID)
);

CREATE TABLE IF NOT EXISTS GERENTES (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    BONUS DECIMAL(8,2),
    CONSTRAINT FK_GERENTE_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS (ID)
);
